language: python

python:
  - "2.7"

env:
  - TOX_ENV=py26
  - TOX_ENV=py27

install:
  - travis_retry pip install -U pip wheel tox
  - travis_retry pip install -U -r requirements.txt -e .

script:
  - tox -e $TOX_ENV
