language: python

python:
  - "3.4"

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34

install:
  - travis_retry pip install -U pip wheel tox
  - travis_retry pip install -U -r requirements.txt -e .

script:
  - tox -e $TOX_ENV
